### ISSUE TITLE
Migrate from `traverse` to `neotraverse`

### ISSUE THREAD

**Issue by trivikr** [wl-online-payments-direct/sdk-nodejs#7]
**Is your feature request related to a problem? Please describe.**

The [Ecosystem Performance](https://e18e.dev/) was formed in July 2024 to cleanup, speedup, levelup the JavaScript Ecosystem.
Socket Security team wrote a blog post about it https://socket.dev/blog/javascript-community-launches-e18e-initiative-to-improve-ecosystem-performance

On the e18e cleanup channel on Discord, multiple solutions are being discussed. One of them is to replace `traverse` with `neotraverse`, which reduces install size by around 3.5 MB and number of dependencies by 65.
For details, check blog post https://puruvj.dev/blog/forking-and-fixing-traverse

The wl-online-payments-direct/sdk-nodejs depends on traverse
https://github.com/wl-online-payments-direct/sdk-nodejs/blob/0ef79fc251215c9659d5c4e1b00c9f71835c7865/package.json#L17

**Describe the solution you'd like**

Migrate from `traverse` to `neotraverse`

There's a codemod available in https://github.com/es-tooling/module-replacements-codemods to migrate from traverse to neotraverse

**Comment by worldline-direct-support-team** [comment]
Hello trivikr,

Thank you for bringing this to our attention. We will look into this and, when necessary, make the required changes.

Kind regards,
Worldline Online Payments Support

**Comment by worldline-direct-support-team** [comment]
Hello @trivikr,

We looked in the library you suggested and it does what you say. 
However, we took a deep look and decided to use recursive methods instead of the traverse, so we completely removed the traverse library from our repo. 

We would like to inform you that these changes will be available in the next release.

Kind regards,
Worldline Online Payments Support
